Trip_wallet/Trip_wallet/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Trip_wallet/webapp/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required


app_name = 'webapp'

urlpatterns = [
    path('', views.WellcomeView.as_view(), name = 'Wellcome'),

    # register
    path('register/', views.UserRegisterFormView.as_view(), name='register'),

    # user details update
    # details/12/edit
    path('details/<int:pk>/edit/', login_required(views.UserDetailsUpdateView.as_view()), name='userDetailsUpdate'),

    # user details delete
    # details/12/delete
    path('details/<int:pk>/delete/', login_required(views.UserDetailsDeleteView.as_view()), name='UserDetailsDelete'),

    # user details view
    # dtails/12/
    path('details/<int:pk>/', login_required(views.UserDetailsView.as_view()), name = 'UserDetails'),

    # Log in
    path('login/', views.UserLoginFormView.as_view(), name = 'Login'),
    # Log out
    path('logout/', views.logout_view, name='Logout'),

    # Reset password
    # newpassword/12/
    path('newpassword/<int:pk>/', login_required(views.ResetPasswordView.as_view()), name = 'ResetPassword'),

    # Forgot password
    # login/forgot/
    path('login/forgot/', views.UserForgotPasswordView.as_view() , name = 'ForgotPassword'),

    # Create trip
    # trip/add/
    path('trip/add/', login_required(views.TripCreateView.as_view()), name = 'TripCreate'),

    # Trips list
    # trip/
    path('trip/', login_required(views.MyTripsView.as_view()), name = 'TripList'),
    # activate button
    # trip/12/activate/
    path('trip/<int:pk>/activate', login_required(views.tripActivateView.as_view()), name = 'tripActivate'),

    # Trip details
    # trip/12/
    path('trip/<int:pk>/', login_required(views.TripDetailsView.as_view()), name = 'TripDetails'),

    # Trip addNewPurchaseTransaction
    # trip/12/
    path('trip/<int:pk>/addPurchaseTransaction/', login_required(views.TripNewPurchaseTransactionView.as_view()), name = 'TripNewPurchaseTransaction'),

    # Trip addNewDonationTransaction
    # trip/12/
    path('trip/<int:pk>/addDonationTransaction/', login_required(views.TripNewDonationTransactionView.as_view()), name = 'TripNewDonationTransaction'),

    # Trip addNewInternalTransaction
    # trip/12/
    path('trip/<int:pk>/addInternalTransaction/', login_required(views.TripNewInternalTransactionView.as_view()), name = 'TripNewInternalTransaction'),

    # Trip details update
    # trip/12/update/
    path('trip/<int:pk>/update/', login_required(views.TripCreateView.as_view()), name = 'TripDetailsUpdate'),

    # Trip delete
    # trip/12/delete/
    path('trip/<int:pk>/delete/', login_required(views.TripDeleteView.as_view()), name = 'TripDetailsDelete'),

    path('signin/', views.signin, name = 'SIGNIN'),
    path('main/', views.main, name = 'MAIN'),

    path('newtrip/choseTypeUser/', views.choseTypeUser, name = 'Chose user type'),
    path('newtrip/choseTypeUser/addUser', views.addUser, name = 'Add new user'),
    path('newtrip/choseTypeUser/addDummy', views.addDummy, name = 'Add dummy user'),
    path('newtrip/choseTypeUser/addDonator', views.addDonator, name = 'Add donator'),
    path('main/nekstr/', views.myTrip, name = 'My trip'),
    path('main/nekstr/choseTypeTransaction/', views.choseTypeTransaction, name = 'Chose transaction type'),
    path('main/nekstr/choseTypeTransaction/transactionReceipt', views.transactionReceipt, name = 'Receipt transaction'),
    path('main/nekstr/choseTypeTransaction/transactionDonation', views.transactionDonation, name = 'Donation transaction'),
    path('main/nekstr/choseTypeTransaction/transactionInternal', views.transactionInternal, name = 'Internal transaction'),
    path('main/nekstr/choseTypeTransaction/addDonator', views.addDonator, name = 'Add donator'),

]

Trip_wallet/webapp/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth.models import User


#dodati jim je treba funkcijonalnost

class PersonalInformation(models.Model):
    user = models.OneToOneField(User, related_name='user', on_delete=models.CASCADE)
    country = models.CharField(max_length=250, blank=True, null=True)
    city = models.CharField(max_length=250, blank=True, null=True)
    address = models.CharField(max_length=250, blank=True, null=True)
    post = models.CharField(max_length=250,blank=True, null=True)
    postal_code = models.CharField(max_length=10,blank=True, null=True)
    birth_date = models.DateField(blank=True, null=True)
    telephone_number = models.CharField(max_length=20, blank=True, null=True)
    image = models.ImageField(blank=True, null=True)
    tax_number = models.CharField(max_length=20, blank=True, null=True)
    creator = models.ForeignKey(User, related_name='creator', on_delete=models.SET_NULL, blank=True, null=True)
    user_type = models.CharField(max_length=30, blank=True, null=True)

    def __str__(self):
        return self.user.username


# class ExchangeRate(models.Model):
#     currancy = models.CharField(max_length=30, blank=True)
#     value = models.FloatField(blank=True)

class Country(models.Model):
    country = models.CharField(max_length=250)

    def __str__(self):
        return self.country

class Trip(models.Model):
    trip_name = models.CharField(max_length=250)
    country = models.ManyToManyField(Country, related_name='countryFk')
    friends = models.ManyToManyField(User, related_name='participant')
    description =  models.CharField(max_length=2500, blank=True)
    is_active = models.BooleanField(default=True)
    time_stamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.trip_name

class Transaction(models.Model):
    time_stamp = models.DateTimeField(auto_now_add=True)
    value = models.FloatField(blank=True)
    user_payed = models.ForeignKey(User, related_name='user_payed', on_delete=models.PROTECT)
    user_recieved = models.ForeignKey(User, related_name='user_recieved', on_delete=models.PROTECT, null=True, blank=True)
    type = models.CharField(max_length=30)
    image = models.ImageField(blank=True, null=True)
    receiver = models.CharField(max_length=250)
    comment = models.CharField(max_length=1000, blank=True, null=True)
    trip = models.ForeignKey(Trip, related_name='Trip', on_delete=models.PROTECT)
    involved = models.ManyToManyField(User, related_name='involved')

# class TransactionInvolvment(models.Model):
#     transaction = models.ManyToManyField(Transaction, related_name='transaction_involvment')
#     user = models.ManyToManyField(User, related_name='user_involvment')
#     weight = models.FloatField(blank=False, null=False)
#
# class TransactionLabels(models.Model):
#     transaction = models.ManyToManyField(Transaction, related_name='transaction_label')
#     label = models.CharField(max_length=100)

Trip_wallet/webapp/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.mail import send_mail
from django.db.models import Sum
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views import generic
from django.views.generic import View
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import *
from .forms import *
from random import choice
from string import ascii_letters


# wellcome page
# ''
class WellcomeView(View):
    template_name = 'webapp/wellcome.html'

    def get(self, request):
        return render(request, self.template_name)

#new internal transaction for trip
class TripNewInternalTransactionView(View):
    form_class = CreateTripNewInternalTransaction
    model = Trip
    template_name = 'webapp/tripAddInternalTransaction.html'

    # display a new form
    def get(self, request, pk):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            payer=dict(request.POST)['payer']
            country = dict(request.POST)['country']
            friends = dict(request.POST)['friends']
            new_trip = self.model.objects.create(
                trip_name = request.POST['trip_name'],
                description = request.POST['description'],
                is_active = True)
            #for user in friends:
             #   new_trip.friends.add(user)
             #   new_trip.save()
            for user in payer:
                new_trip.payer.add(user)
                new_trip.save()

            for visited in country:
                new_trip.country.add(visited)
                new_trip.save()
            # add creator if he wasn't there
            user = User.objects.get(username=self.request.user).pk
            if user not in friends:
                new_trip.friends.add(user)
                new_trip.save()

            mes = 'You have successfully created new trip.'
            messages.success(request, mes)
            return redirect('webapp:TripList')

        return render(request, self.template_name, {'form': form})

#new donation transaction for trip
class TripNewDonationTransactionView(View):
    form_class = CreateTripNewDonationTransaction
    model = Trip
    template_name = 'webapp/tripAddDonationTransaction.html'

    # display a new form
    def get(self, request,pk):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            payer=dict(request.POST)['payer']
            country = dict(request.POST)['country']
            friends = dict(request.POST)['friends']
            new_trip = self.model.objects.create(
                trip_name = request.POST['trip_name'],
                description = request.POST['description'],
                is_active = True)
            #for user in friends:
             #   new_trip.friends.add(user)
             #   new_trip.save()
            for user in payer:
                new_trip.payer.add(user)
                new_trip.save()

            for visited in country:
                new_trip.country.add(visited)
                new_trip.save()
            # add creator if he wasn't there
            user = User.objects.get(username=self.request.user).pk
            if user not in friends:
                new_trip.friends.add(user)
                new_trip.save()

            mes = 'You have successfully created new trip.'
            messages.success(request, mes)
            return redirect('webapp:TripList')

        return render(request, self.template_name, {'form': form})

#new purchase transaction for trip
class TripNewPurchaseTransactionView(View):
    form_class = CreateTripNewPurchaseTransaction
    model = Trip
    template_name = 'webapp/tripAddPurchaseTransaction.html'

    # display a new form
    def get(self, request, pk):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    def post(self, request, pk):
        form = self.form_class(request.POST)
        if form.is_valid():
            # pridobimo parametre iz POST zahtevka
            payer = None
            payer_id = int(request.POST['payer'])
            cost = list(dict(request.POST)['cost'])[0]
            involved = dict(request.POST)['involved']
            receiver = dict(request.POST)['receiver']
            note = dict(request.POST)['note']
            trip = None
            try:
                # poiščemo User objekt, ki se nahaja pod payer_id
                payer = User.objects.get(id=payer_id)
            except  User.DoesNotExist:
                pass

            trip = Trip.objects.get(id=pk)

            # skreirajmo novo vrstico v tabeli Transaction
            transaction = Transaction.objects.create(
                value = cost,
                user_payed = payer,
                receiver = receiver,
                trip = trip,
                comment = note,
                type = 'Purchase'
            )
            transaction.involved.set(involved)

            # shranimo novo vrstico
            transaction.save()

            mes = 'You have successfully saved your transaction.'
            messages.success(request, mes)
            return redirect('webapp:TripList')

        return render(request, self.template_name, {'form': form})
# create new user
# register/
class UserRegisterFormView(View):
    # iz kje dobimo podatke
    form_class = UserRegisterForm
    template_name = 'webapp/registration_form.html'

    # display a new form
    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    # process form data
    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():
            # storing it localy not to DB
            user = form.save(commit=False)

            # cleaned (normalized data)
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            # You need to save the password in hash otherwise you will get
            # a bunch of errors
            user.set_password(password)
            user.save()

            # returns User objects if credentials are correct
            user = authenticate(username=username, password=password)

            if user is not None:
                if user.is_active:
                    login(request, user)
                    # creates some personal informations
                    form_personal_class = UserPersonalInfoForm
                    form_personal = form_personal_class(None)
                    personal_info = form_personal.save(commit=False)
                    personal_info.user = self.request.user
                    personal_info.user_type = 'normal'
                    personal_info.save()
                    pk = PersonalInformation.objects.get(user=self.request.user).pk
                    # add a message
                    mes1 = 'Hi ' + str(request.user) + '! You have succsessfully created your account. =)'
                    mes2 = 'Just one more step and you are done!'
                    messages.success(request, mes1)
                    messages.success(request, mes2, extra_tags='delay')
                    return redirect('webapp:userDetailsUpdate', pk = pk)

        return render(request, self.template_name, {'form': form})


# Update details view for user
# details/12/edit
class UserDetailsUpdateView(View):
    form_personal_class = UserPersonalInfoForm
    model_personal = PersonalInformation
    form_user_class = UserCreateForm
    model_user = User
    template_name = 'webapp/userDetails_form.html'

    def get(self, request, pk):
        if (self.model_personal.objects.get(user=request.user).pk == pk) or (request.user.is_superuser):
            instance_personal = self.model_personal.objects.get(id=pk)
            form_personal = self.form_personal_class(instance=instance_personal)
            instance_user = self.model_user.objects.get(pk=instance_personal.user.pk)
            form_user = self.form_user_class(instance=instance_user)
            return render(request, self.template_name, {'form_personal': form_personal, 'form_user': form_user, 'pk': pk})
        else:
            messages.error(request, 'You do not have the permission to view this page!')
            return redirect('webapp:MAIN')

    def post(self, request, pk):
        if (self.model_personal.objects.get(user=request.user).pk == pk) or (request.user.is_superuser):
            form_personal = self.form_personal_class(request.POST, request.FILES)
            form_user = self.form_user_class(request.POST)
            if form_user.is_valid() and form_personal.is_valid():
                instance_personal = self.model_personal.objects.get(id=pk)
                instance_user = User.objects.get(pk = instance_personal.user.pk)
                # this part is nasty :(
                user_new = form_user.save(commit=False)
                instance_user.first_name = user_new.first_name
                instance_user.last_name = user_new.last_name
                instance_user.email = user_new.email
                instance_user.save()

                personal_new = form_personal.save(commit=False)
                instance_personal.country = personal_new.country
                instance_personal.city = personal_new.city
                instance_personal.address = personal_new.address
                instance_personal.post = personal_new.post
                instance_personal.postal_code = personal_new.postal_code

Trip_wallet/webapp/templates/webapp/choseTypeUser.html
{% extends 'webapp/head.html' %}
{% block new_user_active %}active{% endblock %}
{% block content %}
  <div class="container-fluid unique">
        <h1 class="title text-uppercase text-center">Chose type of user</h1>
        <div class="row" margin-top="150px">
            <div class="col-lg-4 offset-lg-0">
                <div class="forma">
                    <a href="{{ request.path }}addUser" id="realUser_link" class="link">
                        <h1 class="text-uppercase text-center">Real user</h1><i class="fa fa-user illustration text-center" style="color:inherit"></i></a>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="forma">
                    <a href="{{ request.path }}addDummy" id="fakeUser_link" class="link">
                        <h1 class="text-uppercase text-center">Fake user</h1><i class="fa fa-user-secret illustration text-center" style="color:inherit"></i></a>
                </div>
            </div>
            <div class="col-lg-4 offset-lg-0">
                <div class="forma">
                    <a href="{{ request.path }}addDonator" id="donator_link" class="link">
                        <h1 class="text-uppercase text-center">Donator</h1><i class="fa fa-bank illustration text-center" style="color:inherit"></i></a>
                </div>
            </div>
        </div>
        <div class="row" style="margin-top:30px">
            <div class="col-lg-4 offset-lg-4">
                <div class="forma">
                  <a href="../" id="back_link" class="link">
                      <h1 class="text-uppercase text-center" style="color:inherit">back</h1>
                  </a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

Trip_wallet/webapp/templates/webapp/forgot.html
{% extends 'webapp/head.html' %}
{% block title %}Password reset{% endblock %}

{% block content %}
  <div class="container-fluid unique">
    <div class="row">
        <div class="col-lg-4 offset-lg-4">
            {% include 'webapp/messages.html' %}
            <div class="forma" style="margin-top: 8rem">
                <form class="form-horisontal" action="" method="post">
                  {% csrf_token %}
                  {% include 'webapp/form-template.html' %}
                  <div class="form-group">
                      <div class="col-lg-4 offset-4">
                          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">
                              <span class="fa fa-envelope-o" aria-hidden="true"></span>&nbsp;
                              Send email
                          </button>
                      </div>
                  </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

</body>

</html>

Trip_wallet/webapp/templates/webapp/head.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> {% block title %} Trip wallet {% endblock %} </title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'webapp/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'webapp/fonts/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'webapp/fonts/ionicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'webapp/fonts/material-icons.min.css' %}">
    <link rel="stylesheet" href="{% static 'webapp/fonts/simple-line-icons.min.css' %}">
    <link rel="stylesheet" href="{% static 'webapp/css/styles.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css">

</head>

<body>
    <script src="{% static 'webapp/js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'webapp/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'webapp/js/script.min.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>

    <nav class="navbar navbar-dark bg-dark navbar-expand-lg">
        <div class="container-fluid">

          <!-- logo -->
          <a class="navbar-brand" href="{% url 'webapp:Wellcome' %}">Trip wallet</a>

          <!-- navigation toggler -->
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#topNavbar" aria-controls="topNavbar" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
          </button>

          <!-- navigation buttons -->
          <div class="collapse navbar-collapse" id="topNavbar">

              <!-- check for authentication and display options -->
              {% if user.is_authenticated %}

              <ul class="navbar-nav mr-auto mt-2 mt-lg-0">

                  <!-- trips dropdown -->
                  <li class="nav-item dropdown {% block trip_active %}{% endblock %}">
                      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <span class="fa fa-road" aria-hidden="true"></span>&nbsp;
                        Trips
                      </a>
                      <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                          <a class="dropdown-item {% block trip_active_trip %}{% endblock %}" href="{% url 'webapp:TripList' %}">My trips</a>
                          <a class="dropdown-item {% block trip_active_new %}{% endblock %}" href="{% url 'webapp:TripCreate' %}">Create New Trip</a>
                      </div>
                  </li>

                  <!-- add new user -->
                  <li class="nav-item dropdown {% block new_user_active %}{% endblock %}">
                      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <span class="fa fa-user-plus" aria-hidden="true"></span>&nbsp;
                        Add user
                      </a>
                      <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                          <a class="dropdown-item {% block new_real_user_active %}{% endblock %}" href="{% url 'webapp:Add new user' %}">New User</a>
                          <a class="dropdown-item {% block new_fake_user_active %}{% endblock %}" href="{% url 'webapp:Add dummy user' %}">Fake User</a>
                          <a class="dropdown-item {% block new_donator_user_active %}{% endblock %}" href="{% url 'webapp:Add donator' %}">Donator</a>
                      </div>
                  </li>

                  <!-- user details-->
                  <li class="nav-item {% block user_details_active %}{% endblock %}">
                      <a class="nav-link" href="{% url 'webapp:UserDetails' request.user.user.pk %}">
                          <span class="icon ion-user" aria-hidden="true"></span>&nbsp;
                          My account
                      </a>
                  </li>
              </ul>

              <ul class="navbar-nav">
                  <!-- search -->
                  <form class="form-inline my-2 my-lg-0">
                      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                      <input class="form-control mr-sm-2" type="search" placeholder="Search">
                  </form>

                  <!-- login -->
                  <li class="nav-item">
                      <a class="nav-link" href="{% url 'webapp:Logout' %}">
                      <span class="fa fa-power-off" aria-hidden="true"></span>&nbsp; Logout</a>
                  </li>
              </ul>

              <!-- if not loged in -->
              {% else %}
              <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                <li class="nav-item {% block register %}{% endblock %}">
                    <a class="nav-link" href="{% url 'webapp:register' %}">
                        <span class="fa fa-user-plus" aria-hidden="true"></span>&nbsp;
                        Register
                    </a>
                </li>
              </ul>
              <ul class="navbar-nav">
                  <li class="nav-item">
                      <a class="nav-link" href="{% url 'webapp:Login' %}">
                      <span class="fa fa-power-off" aria-hidden="true"></span>&nbsp; Login</a>
                  </li>
              </ul>
              {% endif %}
            </div>
        </div>
    </nav>

    {% block content %}
    {% endblock %}
    {% if user.is_authenticated %}
        <span class="small" style="color: rgba(80,80,80,0.7);position: absolute;top: 4rem;right: 16px;font-size: 10px;"> Signed in as: {{request.user}} </span>
    {% endif %}
</body>

</html>

Trip_wallet/webapp/templates/webapp/registration_form.html
{% extends "webapp/head.html" %}
{% block title %} Register {% endblock %}
{% block register %}active{% endblock %}

{% block content %}
  <div class="container-fluid unique">
      <div class="row">
          <div class="col-lg-6 offset-lg-3">
              <div class="forma" style="margin-top: 30px">
                  <div class="illustration"><i class="fa fa-user-plus illustration"></i></div>
                  {% if error_message %}
                      <p><strong> {{error_message}} </strong></p>
                  {% endif %}
                  <form class="form-horisontal" action="" method="post" role="form" enctype="multipart/form-data">
                      {% csrf_token %}
                      {% include 'webapp/form-template.html' %}

                      <div class="form-group">
                          <div class="col-lg-4 offset-lg-4">
                              <button class="btn btn-outline-success" type="submit">Create New Account</button>
                          </div>
                      </div>
                  </form>
                  <div class="form-group">
                      <div class="row">
                          <div class="col"><a href="{% url 'webapp:Login' %}" class="link">Already have an account? Log in.</a></div>
                      </div>
                  </div>
              </div>
          </div>
      </div>
  </div>
{% endblock %}

Trip_wallet/webapp/templates/webapp/resetpassword_form.html
{% extends "webapp/head.html" %}
{% block title %}Reset Password{% endblock %}
{% block content %}
<div class="container-fluid unique">
    <div class="row">
        <div class="col-lg-6 offset-lg-3">
            {% include 'webapp/messages.html' %}

            <div class="forma" style="margin-top: 30px">
                <div class="offset-3 col-lg-9">
                    <span class="text-danger small"> {{mes}} </span>
                </div>
                <form class="form-horisontal" action="" method="post" role="form">
                    {% csrf_token %}
                    {% include 'webapp/form-template.html' %}

                    <div class="col-lg-4">
                        <button class="btn btn-outline-success btn-block" type="submit">Reset password</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

Trip_wallet/webapp/templates/webapp/tripAddDonationTransaction.html
{% extends 'webapp/head.html' %}
{% block title %}Create New Trip{% endblock %}
{% block trip_active %}active{% endblock %}
{% block trip_active_new %}active{% endblock %}
{% block content %}
  <div class="container-fluid unique">
        <div class="row">
            <div class="col-lg-6 offset-3">
                {% include 'webapp/messages.html' %}
                <div class="forma" style="margin-top: 30px">
                    <form class="form-horisontal" action="" method="post">
                      <h4 style="margin-bottom: 20px">New Donation Transaction</h4>
                      <div class="form-group">
                          {% csrf_token %}
                          {% include 'webapp/form-template.html' %}
                      </div>
                      <div class="row">
                          <div class="col-lg-4 offset-4">
                              <button class="btn btn-outline-success btn-block" type="submit">Save</button>
                          </div>
                      </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    select-multiple
    <script>
        $(document).ready(function() {
            $('.select-multiple-user').select2({
              placeholder: 'Search by name or lastname',
              allowClear: true
            }).select2('val', []);
            $('.select-multiple-country').select2({
              placeholder: 'You can select multiple countries',
              allowClear: true
            }).select2('val', []);
        });
    </script>
{% endblock %}

Trip_wallet/webapp/templates/webapp/tripAddPurchaseTransaction.html
{% extends 'webapp/head.html' %}
{% block title %}New purchase transaction{% endblock %}
{% block trip_active %}active{% endblock %}
{% block content %}
  <div class="container-fluid unique">
        <div class="row">
            <div class="col-lg-6 offset-3">
                {% include 'webapp/messages.html' %}
                <div class="forma" style="margin-top: 30px">
                    <form class="form-horisontal" action="" method="post">
                      <h4 style="margin-bottom: 20px">New Purchase Transaction</h4>
                      <div class="form-group">
                          {% csrf_token %}
                          {% include 'webapp/form-template.html' %}
                      </div>
                      <div class="row">
                          <div class="col-lg-4 offset-4">
                              <button class="btn btn-outline-success btn-block" type="submit">Save</button>
                          </div>
                      </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    select-multiple
    <script>
        $(document).ready(function() {
            $('.select-multiple-user').select2({
              placeholder: 'Search by name or lastname',
              allowClear: true
            }).select2('val', []);
            $('.select-multiple-country').select2({
              placeholder: 'You can select multiple countries',
              allowClear: true
            }).select2('val', []);
        });
    </script>
{% endblock %}